config/routes.rb
Nbs::Application.routes.draw do

  resources :payment_notifications

  get "agent_home/show"
  get "supplier_home/show"

  devise_for :users, :controllers => {:passwords => "users/passwords"}

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  match 'bulk_action' => 'bulk_actions#create', :as => :bulk_action

  namespace :administration do
    root :to => redirect("/")
    resources :users do
      resource :password, :controller => 'password', :only => [:new, :update, :destroy]
      member do
        get :sign_in_as
      end
    end
    resource :bulk_users_update, :controller => "bulk_users_update", :only => [:update]
    resources :categories
    resources :category_email_templates, :only => [:edit, :update]
    resource :setting, :only => [:edit, :update]
    resources :featured_deals, :only => [:index, :create]
    resources :email_templates
    resources :leads
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resources :articles
    resources :news
    resources :hints
    resources :currencies
    namespace :invoicing do
      resources :invoices do
        resources :invoice_lines
        resource :cash_flow, :only => [:new, :create], :controller => "CashFlow"
        resource :invoice_lines_payable, :only => :new, :controller => "InvoiceLinesPayable"
        resources :mailings, :only => [:new, :create]
        resource :seller, :only => [:update]
      end
      resource :bulk_mailings, :controller => "bulk_mailings", :only => [:edit, :update]
      resource :bulk_invoice_update, :controller => "bulk_invoice_update", :only => [:update]
      resource :bulk_invoice_users, :controller => "bulk_invoice_users", :only => [:update]
      resources :upcoming_invoices, :only => [:index]
      resources :payment_transactions
      resources :credit_notes
      resources :creditors
      resources :refunds
    end
    resources :bank_accounts
    resources :vat_rates
    resources :lead_templates
    resources :sellers
    resources :category_users
    resources :countries
    resource :translation do
      resource :cache
    end
    resource :stats_recalculation, :controller => "stats_recalculation", :only => [:update]
    resources :supplier_interests, :only => [:edit, :update]
    resources :youtube_introductions
    resources :email_bounces
    resources :languages
    resources :subscription_plans
  end

  namespace :suppliers do
    root :to => "lead_purchases#index"
    resources :cart_items
    resources :deal_certification_requests, :only => [:index, :edit, :update]
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :cart, :only => [:show, :update, :destroy], :controller => 'cart'
    resources :lead_purchases do
      collection do
        put :bulk_update
      end
      resource :lead_email, :only => [:new, :create]
    end
    resource :bulk_cart_items, :controller => "bulk_cart_items", :only => [:create]
  end
  match 'suppliers/bulk_lead_purchase_csv' => 'suppliers/bulk_lead_purchase_csv#create', :as => "bulk_lead_purchase_csv"
  match 'suppliers/bulk_lead_purchase_print' => 'suppliers/bulk_lead_purchase_print#create', :as => "bulk_lead_purchase_print"
  match 'suppliers/bulk_lead_purchase_update' => 'suppliers/bulk_lead_purchase_update#create', :as => "bulk_lead_purchase_update"
  match 'suppliers/bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#new', :as => "bulk_lead_share_by_email"
  match 'suppliers/create_bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#create', :as => "create_bulk_lead_share_by_email"

  namespace :call_centres do
    root :to => "call_centre_agents#index"
    resources :call_centre_agents do
      resource :password, :controller => 'password', :only => [:new, :update, :destroy]
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :bulk_call_centre_agents_update, :controller => "bulk_call_centre_agents_update", :only => [:update]
    resources :leads
    resources :lead_templates
    resources :news
  end

  namespace :call_centre_agents do
    root :to => "leads#index"
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :lead_users do
    root :to => "lead_purchases#index"
    resources :lead_purchases do
      resource :lead_email, :only => [:new, :create]
    end
    resources :lead_requests
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:create, :destroy]
    resource :bulk_lead_purchase_update, :controller => "bulk_lead_purchase_update", :only => [:create]
    resource :bulk_lead_purchase_csv, :controller => "bulk_lead_purchase_csv", :only => [:create]
    resource :bulk_lead_purchase_print, :controller => "bulk_lead_purchase_print", :only => [:create]
  end

  namespace :suppliers do
    root :to => redirect("/suppliers/lead_purchases")
    resource :interests, :only => [:edit, :update]
    resources :subaccounts
    resources :lead_requests, :only => [:index, :update, :destroy]
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:destroy, :update]
    resource :bulk_subaccounts_update, :controller => "bulk_subaccounts_update", :only => [:update]
    resources :not_invoiced_leads, :only => [:index]
    resources :invoices, :only => [:show, :index]
    resources :lead_templates
  end

  namespace :agents do
    root :to => "leads#index"
    resources :lead_templates
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :members do
    root :to => "leads#index"
    resources :leads, :path => :requests
    resources :tenders, :path => :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
  end

  namespace :callers do
    resources :campaigns do
      resources :materials
      member do
        get 'result_details'
        get 'result_details_to_csv'
        get 'contacts_for_search'
        post 'duplicate'
      end
      resources :results, :except => :show do
        collection do
          post 'batch_assign'
        end
      end
      resources :campaigns_users, :only => [:index, :update]
      resource :campaigns_description, :controller => "campaigns_description", :only => [:show, :edit, :update]
      resources :contacts do
        collection do
          post 'batch_remove'
          post 'batch_assign'
          post 'bulk_contacts_export_csv'
          post 'import_xls'
        end
      end
      resources :advanced_import, :only => [:create, :destroy] do
        collection do
          post 'choose'
          post 'preview'
        end
      end
      resources :agent_work_screen, :only => :index
      namespace :agent_work_screen do
        resources :contacts, :only => [:create, :show, :destroy, :update] do
          resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
        end
        resource :agent_information, :only => [:show]
        resource :call_sheet, :only => [:show]
        resource :pending_call, :only => [:show]
        resource :complete_contact, :only => [:show]
      end
      resources :email_templates, :only => [:edit, :update]
    end

    resource :production, :controller => "production", :only => [:show]

    resources :contacts do
      resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
    end

    resources :campaign_reports, :only => [:index] do
      collection do
        post 'load_agents'
      end
    end
  end

  namespace :comments do
    resources :threads
    resources :leads do
      resources :threads
    end
    resources :replies
    resources :blocked_conversations, :only => [:create, :destroy]
    resources :comment_readers, :only => [:create]
  end

  namespace :deal_comments do
    resources :threads
    resources :deals do
      resources :threads
    end
    resources :replies
    resources :comment_readers, :only => [:create]
  end

  match 'supplier_home' => 'supplier_home#show', :as => "supplier_home"
  match 'agent_home' => 'agent_home#show', :as => "agent_home"
  match 'member_home' => 'member_home#show', :as => "member_home"

  resources :leads, :except => [:new, :create, :destroy] do
    collection do
      post :creators
    end
  end

  resources :deals, :except => [:new, :create, :destroy] do
    member do
      post 'rate'
    end
  end

  resources :group_deals, :only => [:show]

  resources :categories, :only => [:index] do
    resources :more_leads_requests, :only => [:new, :create]
  end
  resources :deal_categories, :only => [:index]

  match 'categories/:slag' => "leads#index"
  match 'categories/deals/:slag' => "deals#index", :as => :deals_index

  resource :contacts_advanced_import, :only => [:create, :destroy, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :leads_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :members_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :suppliers_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resources :agent_accounts, :only => [:new, :create]
  resources :supplier_accounts, :only => [:new, :create]
  resources :member_accounts, :only => [:new, :create]
  resources :category_supplier_accounts, :only => [:new, :create]

app/controllers/administration/news_controller.rb
class Administration::NewsController < Administration::AdministrationController
  inherit_resources

  set_tab "content"
  set_subtab "news"

  def edit
    @news = Article.find(params[:id])
    edit!
  end

  def update
    @news = Article.find(params[:id])
    @news.attributes = params[:news]
    update!
  end

  def create
    @news = "Article::News::#{params[:subclass]}".constantize.new
    create! do |success,failure|
      success.html { render :action => :edit }
      failure.html { redirect_to administration_news_index_path }
    end
  end

  def show
    @news = Article.find(params[:id])
    show!
  end

  def destroy
    @news = Article.find(params[:id])
    super do |format|
      format.html { redirect_to administration_news_index_path }
    end
  end

  protected

  def collection
    params[:search] ||= {}
    params[:search][:with_subclass] = "Article::News" unless params[:search][:with_subclass].present?
    @search = Article.scoped_search(params[:search])
    @news = @search.paginate(:page => params[:page])
  end

end

app/controllers/call_centres/bulk_call_centre_agents_update_controller.rb
class CallCentres::BulkCallCentreAgentsUpdateController < CallCentres::CallCentreController

  def update
    User::CallCentreAgent.where({:parent_id => current_user.id}).where("id in (?)", params[:call_centre_agent_ids]).each do |user|
      user.locked = params[:bulk_action_type]
      user.save
    end
    flash[:notice] = I18n.t("flash.bulk_call_centre_agents_update.update.notice")
    redirect_to call_centres_call_centre_agents_path
  end

end

app/controllers/call_centres/call_centre_agents_controller.rb
class CallCentres::CallCentreAgentsController < CallCentres::CallCentreController

  set_tab "call_centre_agents"

  def index
    per_page = params[:per_page].blank? ? 25 : params[:per_page].to_i
    params[:search] ||= {}
    params[:search][:with_subaccounts] = current_user.id

    @search = User::CallCentreAgent.scoped_search(params[:search])
    @call_centre_agents = if per_page == 0
               @search.all
             else
               @search.paginate(:per_page => per_page, :page => params[:page])
             end
  end

  def new
    @call_centre_agent = User::CallCentreAgent.new
  end

  def create
    @call_centre_agent = User::CallCentreAgent.new(params[:user_call_centre_agent])
    @call_centre_agent.parent_id = current_user.id
    @call_centre_agent.skip_email_verification = params[:user_call_centre_agent][:skip_email_verification]
    if @call_centre_agent.save
      flash[:notice] = t("call_centre.call_centre_agents.create.flash.call_centre_agent_creation_successful")
      redirect_to call_centres_call_centre_agents_path
    else
      render :action => 'new'
    end
  end

  def edit
    @call_centre_agent = User::CallCentreAgent.find(params[:id])
  end

  def update
    @call_centre_agent = User::CallCentreAgent.find(params[:id])
    user_params = params["user_call_centre_agent".to_sym]
    if user_params and user_params[:locked]
      @call_centre_agent.locked = user_params[:locked]
    end
    if @call_centre_agent.update_attributes(user_params)
      flash[:notice] = I18n.t("call_centre.call_centre_agents.update.flash.call_centre_agent_update_successful")
      redirect_to call_centres_call_centre_agents_path
    else
      render :action => 'edit'
    end
  end

  def destroy
    @call_centre_agent = User::CallCentreAgent.find(params[:id])
    if @call_centre_agent.destroy
      flash[:notice] = I18n.t("call_centre.call_centre_agents.destroy.flash.call_centre_agent_deletion_successful")
    else
      flash[:notice] = I18n.t("call_centre.call_centre_agents.destroy.flash.call_centre_agent_deletion_failure")
    end
    redirect_to call_centres_call_centre_agents_path
  end
end

app/controllers/call_centres/call_centre_controller.rb
class CallCentres::CallCentreController < SecuredController
  def current_user
    @call_centre ||= ::User::CallCentre.find_by_id(super.id)
  end

  private

  def authorize_user_for_namespace!
    authorize_role(:call_centre)
  end
end

app/controllers/call_centres/deal_assets_controller.rb
class CallCentres::DealAssetsController < CallCentres::CallCentreController
  before_filter :set_deal
  before_filter :set_asset, :except => :create

  include ::DealAssetActions

  private

  def path
    edit_call_centres_deal_path(@deal)
  end

end

app/controllers/call_centres/deals_controller.rb
class CallCentres::DealsController < CallCentres::CallCentreController
  before_filter :set_deal, :only => [:edit, :update, :destroy]
  before_filter :prepare_assets, :only => [:edit, :update]
  before_filter :check_user

  include ::DealActions
  include ::DealCreateActions

  private

  def success(message)
    flash[:notice] = message
    redirect_to call_centres_deals_path
  end

end

app/controllers/call_centres/lead_templates_controller.rb
class CallCentres::LeadTemplatesController < CallCentres::CallCentreController
  inherit_resources

  set_tab "browse_leads"

  def new
    @lead_template = LeadTemplate.new(:current_user => current_user, :creator => current_user, :category_id => params[:lead_template].blank? ? nil : params[:lead_template][:category_id])
    @lead_template.duplicate_fields(LeadTemplate.with_creator(current_user.id).find_by_id(params[:template_id]))
  end

  def create
    @lead_template = LeadTemplate.new(:current_user => current_user, :creator => current_user)
    @lead_template.attributes = params[:lead_template]

    create! do |success, failure|
      success.html { redirect_to call_centres_lead_templates_path }
      failure.html { render 'new' }
    end
  end

  def update
    @lead_template = LeadTemplate.find(params[:id])
    @lead_template.current_user = current_user
    if current_user != @lead_template.creator
      params[:lead_template].delete(:lead_template_fields_attributes)
    end

    update! do |success, failure|
      success.html { redirect_to call_centres_lead_templates_path }
      failure.html { render 'edit' }
    end
  end

  def destroy
    @lead_template = LeadTemplate.find(params[:id])
    @lead_template.current_user = current_user

    if @lead_template.destroy
      flash[:notice] = I18n.t("call_centre.lead_templates.destroy.flash.deletion_successful")
    else
      flash[:notice] = I18n.t("call_centre.lead_templates.destroy.flash.deletion_failure")
    end
    redirect_to :back
  end

  protected

  def collection
    params[:search]||={}
    params[:search][:with_creator] = current_user.id

    @search = LeadTemplate.scoped_search(params[:search])
    @lead_templates = @search.paginate(:page => params[:page], :per_page => LeadTemplate.per_page)
    @categories = LeadCategory.without_locked.with_call_centre_unique(current_user).map { |c| [c.name, c.id] }
  end
end

app/controllers/call_centres/password_controller.rb
class CallCentres::PasswordController < CallCentres::CallCentreController

  before_filter :fetch_user

  private

  def fetch_user
    @user = User.find(params[:call_centre_agent_id])
  end

  public

  def destroy
    @user.send_reset_password_instructions
    flash[:notice] = t("password.flashes.reset")
    redirect_to edit_call_centres_call_centre_agent_path(@user)
  end

  def update
    @user = @user.with_role
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.save
      flash[:notice] = t("password.flashes.successfully_changed")
      redirect_to edit_call_centres_call_centre_agent_path(@user)
    else
      flash[:alert] = t("password.flashes.not_changed")
      render :action => :new
    end
  end
end

app/helpers/call_centres/agent_work_screen/contacts/call_results_helper.rb
module CallCentres::AgentWorkScreen::Contacts::CallResultsHelper
end

app/helpers/call_centres/agent_work_screen/contacts_helper.rb
module CallCentres::AgentWorkScreen::ContactsHelper
end

app/views/call_centres/news/_form.html.erb
<div class="pdd_10 no_pdd_t">
  <fieldset class="inputs labels_100 labels_ta_r">
    <ol>
      <%= form.input :title %>
      <%= form.input :content,
                        :label => false,
                        :as => :ckeditor,
                        :input_html => {
                            :width => '1085px',
                            :height => '250px',
                            :swf_params => {
                                :resource_type => @news.class.name,
                                :resource_id => @news.id
                                }
                            } %>
      <%= form.input :published %>
    </ol>
  </fieldset>
</div>

app/views/call_centres/news/edit.html.erb
<column-mc:>
  <%= javascript_include_tag :ckeditor %>
  <header back="true">
    <%= t('administration.news.edit.view.header', :name => @news.title) %><%= image_tag_for_locale %>
  </header>

  <%#= link_to t("common.back_link"), administration_news_index_path %>
  <%= form_for @news, :as => :news, :url => call_centres_news_path(@news), :html => {:method => :delete, :id => "delete_news_form"} do |form| %>
  <% end %>

  <%= semantic_form_for @news, :as => :news, :url => call_centres_news_path(@news), :html => {:method => :put} do |form| %>
      <frm title="#{@news.title}" c="todo_delete">
        <param:content>
          <%= render :partial => 'form', :locals => {:form => form} %>
        </param:content>
        <param:actions>
          <ibt c="fltri" icon="save">
            <%= form.submit t("administration.news.edit.view.button_save") %>
          </ibt>
          <ibt c="bt_grey fltri">
            <% if @news.just_created %>
                <%= button_to_function t("common.cancel_link"), "$('#delete_news_form').submit();"  %>
            <% else %>
                <%= button_to_function t("common.cancel_link"), "history.go(-1)"  %>
            <% end %>
          </ibt>
        </param:actions>
      </frm>
  <% end %>

</column-mc:>

app/views/call_centres/news/index.html.erb
<search-box:>
  <div class="search_box">
    <h2><%= t("common.search") %></h2>

    <div class="search_content">
      <%= form_for @search, :url => call_centres_news_index_path do |f| %>
          <fieldset class="inputs_vertical">
            <ol class="no_pdd">
              <li class="string">
                <%= f.label :with_keyword, t("administration.leads.index.search.keyword_label") %>
                <%= f.text_field :with_keyword %>
              </li>
              <li class="commit">
                <ibt c="bt_green" icon="magnify">
                  <%= submit_tag t("administration.news.index.view.search_button") %>
                </ibt>
                <p>
                  <%= bt_clear_filter %>
                </p>
              </li>
            </ol>
          </fieldset>
      <% end %>
    </div>
  </div>
</search-box:>

<column-mc:>

  <header>
    <param:content>
      <%= t("administration.news.index.view.header") %>
    </param:content>

    <param:actions>
          <ul class="header_actions">
            <li class="last">
              <%= bt_link_to :plus, t("administration.news.index.view.new_news"), call_centres_news_index_path, :method => :post %>
            </li>
          </ul>
    </param:actions>
  </header>

  <% if @news.blank? %>
      <%= blank_state_message %>
  <% else %>
      <table id="news_table" class="generic">
        <thead>
        <tr>
          <th class="hl"></th>
          <th><%= link_to t("administration.news.index.view.id"), order_for_scoped_search(:id) %></th>
          <th><%= link_to t("administration.news.index.view.title"), order_for_scoped_search(:title) %></th>
          <th class="ta_r"><%= link_to t("administration.news.index.view.created_at"), order_for_scoped_search(:created_at) %></th>
          <th class="ta_r"><%= link_to t("administration.news.index.view.published"), order_for_scoped_search(:published_date) %></th>
          <th class="ta_r"><%= link_to t("administration.news.index.view.times_read"), order_for_scoped_search(:views_count) %></th>
          <th class="ta_r"><%= t("administration.news.index.view.actions") %></th>
          <th class="hr"></th>
        </tr>
        </thead>
        <tfoot>
        <tr>
          <td class="fl"></td>
          <td colspan="6"></td>
          <td class="fr"></td>
        </tr>
        </tfoot>
        <tbody>
        <% @news.each do |news| %>
            <tr class="<%= cycle("odd", "even") %>">
              <td class="cl"></td>
              <td><%= news.id %></td>
              <td><%= news.title %></td>
              <td class="ta_r"><%= news.created_at %></td>
              <td class="ta_r"><%= news.published_date ? news.published_date : '-' %></td>
              <td class="ta_r"><%= news.views_count %></td>
              <td class="tda ta_r">
                <ul-actions>
                  <li>
                    <%= link_to t("administration.news.index.view.edit_link"), edit_call_centres_news_path(news), :class => "default_action" %>
                  </li>
                  <li>
                    <%= link_to t("administration.news.index.view.show_link"), call_centres_news_path(news) %>
                  </li>
                  <li>
                    <%= link_to t("administration.news.index.view.delete_link"), call_centres_news_path(news), :method => :delete, :confirm => t("administration.news.index.view.delete_confirmation") %>
                  </li>
                </ul-actions>
              </td>
              <td class="cr"></td>
            </tr>
        <% end %>
        <% if will_paginate %>
            <tr class="pagination">
              <td colspan="8" class="ta_c">
                <%= will_paginate @news, :previous_label => '&laquo;', :next_label => '&raquo;' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% end %>

</column-mc:>

app/views/call_centres/news/show.html.erb
<column-mc:>
  <header back="true"><%= t('administration.news.show.view.header') %></header>

  <frm title="#{@news.title}">
    <param:header>
      <%= bt_link_to nil, t("common.edit_link"), call_centres_news_path, :class => "fltr" %>
    </param:header>
    <param:content>
      <div class="pdd_10">
        <%= raw @news.content %>
      </div>
    </param:content>
  </frm>

</column-mc:>