config/routes.rb
    resource :stats_recalculation, :controller => "stats_recalculation", :only => [:update]
    resources :supplier_interests, :only => [:edit, :update]
    resources :youtube_introductions
    resources :email_bounces
    resources :languages
    resources :subscription_plans
  end

  namespace :suppliers do
    root :to => "lead_purchases#index"
    resources :cart_items
    resources :deal_certification_requests, :only => [:index, :edit, :update]
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :cart, :only => [:show, :update, :destroy], :controller => 'cart'
    resources :lead_purchases do
      collection do
        put :bulk_update
      end
      resource :lead_email, :only => [:new, :create]
    end
    resource :bulk_cart_items, :controller => "bulk_cart_items", :only => [:create]
  end
  match 'suppliers/bulk_lead_purchase_csv' => 'suppliers/bulk_lead_purchase_csv#create', :as => "bulk_lead_purchase_csv"
  match 'suppliers/bulk_lead_purchase_print' => 'suppliers/bulk_lead_purchase_print#create', :as => "bulk_lead_purchase_print"
  match 'suppliers/bulk_lead_purchase_update' => 'suppliers/bulk_lead_purchase_update#create', :as => "bulk_lead_purchase_update"
  match 'suppliers/bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#new', :as => "bulk_lead_share_by_email"
  match 'suppliers/create_bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#create', :as => "create_bulk_lead_share_by_email"

  namespace :call_centres do
    root :to => "call_centre_agents#index"
    resources :call_centre_agents do
      resource :password, :controller => 'password', :only => [:new, :update, :destroy]
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :bulk_call_centre_agents_update, :controller => "bulk_call_centre_agents_update", :only => [:update]
    resources :leads
    resources :lead_templates
    resources :news
  end

  namespace :call_centre_agents do
    root :to => "leads#index"
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :lead_users do
    root :to => "lead_purchases#index"
    resources :lead_purchases do
      resource :lead_email, :only => [:new, :create]
    end
    resources :lead_requests
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:create, :destroy]
    resource :bulk_lead_purchase_update, :controller => "bulk_lead_purchase_update", :only => [:create]
    resource :bulk_lead_purchase_csv, :controller => "bulk_lead_purchase_csv", :only => [:create]
    resource :bulk_lead_purchase_print, :controller => "bulk_lead_purchase_print", :only => [:create]
  end

  namespace :suppliers do
    root :to => redirect("/suppliers/lead_purchases")
    resource :interests, :only => [:edit, :update]
    resources :subaccounts
    resources :lead_requests, :only => [:index, :update, :destroy]
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:destroy, :update]
    resource :bulk_subaccounts_update, :controller => "bulk_subaccounts_update", :only => [:update]
    resources :not_invoiced_leads, :only => [:index]
    resources :invoices, :only => [:show, :index]
    resources :lead_templates
  end

  namespace :agents do
    root :to => "leads#index"
    resources :lead_templates
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :members do
    root :to => "leads#index"
    resources :leads, :path => :requests
    resources :tenders, :path => :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
  end

  namespace :callers do
    resources :campaigns do
      resources :materials
      member do
        get 'result_details'
        get 'result_details_to_csv'
        get 'contacts_for_search'
        post 'duplicate'
      end
      resources :results, :except => :show do
        collection do
          post 'batch_assign'
        end
      end
      resources :campaigns_users, :only => [:index, :update]
      resource :campaigns_description, :controller => "campaigns_description", :only => [:show, :edit, :update]
      resources :contacts do
        collection do
          post 'batch_remove'
          post 'batch_assign'
          post 'bulk_contacts_export_csv'
          post 'import_xls'
        end
      end
      resources :advanced_import, :only => [:create, :destroy] do
        collection do
          post 'choose'
          post 'preview'
        end
      end
      resources :agent_work_screen, :only => :index
      namespace :agent_work_screen do
        resources :contacts, :only => [:create, :show, :destroy, :update] do
          resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
        end
        resource :agent_information, :only => [:show]
        resource :call_sheet, :only => [:show]
        resource :pending_call, :only => [:show]
        resource :complete_contact, :only => [:show]
      end
      resources :email_templates, :only => [:edit, :update]
    end

    resource :production, :controller => "production", :only => [:show]

    resources :contacts do
      resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
    end

    resources :campaign_reports, :only => [:index] do
      collection do
        post 'load_agents'
      end
    end
  end

  namespace :comments do
    resources :threads
    resources :leads do
      resources :threads
    end
    resources :replies
    resources :blocked_conversations, :only => [:create, :destroy]
    resources :comment_readers, :only => [:create]
  end

  namespace :deal_comments do
    resources :threads
    resources :deals do
      resources :threads
    end
    resources :replies
    resources :comment_readers, :only => [:create]
  end

  match 'supplier_home' => 'supplier_home#show', :as => "supplier_home"
  match 'agent_home' => 'agent_home#show', :as => "agent_home"
  match 'member_home' => 'member_home#show', :as => "member_home"

  resources :leads, :except => [:new, :create, :destroy] do
    collection do
      post :creators
    end
  end

  resources :deals, :except => [:new, :create, :destroy] do
    member do
      post 'rate'
    end
  end

  resources :group_deals, :only => [:show]

  resources :categories, :only => [:index] do
    resources :more_leads_requests, :only => [:new, :create]
  end
  resources :deal_categories, :only => [:index]

  match 'categories/:slag' => "leads#index"
  match 'categories/deals/:slag' => "deals#index", :as => :deals_index

  resource :contacts_advanced_import, :only => [:create, :destroy, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :leads_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :members_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :suppliers_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resources :agent_accounts, :only => [:new, :create]
  resources :supplier_accounts, :only => [:new, :create]
  resources :member_accounts, :only => [:new, :create]
  resources :category_supplier_accounts, :only => [:new, :create]
  resources :certification_accounts, :only => [:new, :create]
  resources :deal_supplier_accounts, :only => [:new, :create]
  resources :locales
  resources :phone_codes
  resources :regions
  resources :category_requests, :only => [:new, :create]
  resources :deal_requests, :only => [:create]
  resources :category_interests, :only => [:create]

  resources :news
  resources :articles
  resources :help_popups
  resources :login_keys

  resource :my_profile, :controller => "my_profile", :only => [:update] do
    member do
      post 'social_link'
      put 'social_unlink'
      get 'unlink'
      put 'remove_category_supplier'
    end
    resources :subscription_plans, :only => [] do
      collection do
        get 'cancel'
      end
      member do
        get 'upgrade'
        get 'downgrade'
      end
    end
  end

  match 'my_profile' => 'my_profile#edit', :as => "my_profile"

  resource :password, :controller => 'password', :only => [:update]
  match 'password' => 'password#edit', :as => 'password'
  match 'ckeditor/destroy/:id', :to => 'ckeditor#destroy'

  resource :contact_us, :controller => "contact_us", :as => "contact_us", :only => [:new, :create]
  resource :terms_and_conditions, :controller => "terms_and_conditions", :as => "terms_and_conditions", :only => [:show]
  match 'contact_us' => 'contact_us#new', :as => 'contact_us'

  resource :lead_templates

  resource :user_session_log, :controller => "user_session_log", :only => [:create]

  resource :share_deal_by_email, :controller => "share_deal_by_email", :only => [:new, :create]

  resources :deal_maker_users

  resources :deal_maker_materials

  resources :email_templates, :only => [:edit, :update]

  constraints(Fairdeals) do
    match '/(:id)' => "fairdeals_home#show"
  end

  constraints(Faircalls) do
    match '/(:id)' => "agent_home#show"
  end

  match ':slug' => 'category_home#show', :as => :category_home_page
  match ':slug/account/new' => 'category_supplier_accounts#new', :as => :new_category_home_page_account
  match ':slug/account' => 'category_supplier_accounts#create', :as => :category_home_page_account
  match ':slug/leads' => 'category_suppliers/leads#index', :as => :category_home_page_leads

app/models/result.rb
class Result < ActiveRecord::Base

  PENDING_RESULTS = [:call_back, :not_interested_now]

  has_many :call_results
  has_many :contacts, :through => :call_results
  has_many :campaigns_results, :foreign_key => "result_id"
  has_many :campaigns, :through => :campaigns_results, :foreign_key => "result_id"
  belongs_to :creator, :polymorphic => true, :foreign_key => "creator_id"

  has_many :result_fields, :dependent => :destroy
  accepts_nested_attributes_for :result_fields, :allow_destroy => true
  accepts_nested_attributes_for :campaigns_results

  scope :call_log_results, where(:final => false)
  scope :final_results, where(:final => true)
  scope :generic_results, where(:generic => true)
  scope :custom_results, where(:generic => false)

  validates :name, :presence => true
  validate :check_is_reported_and_is_success

  def to_s
    name
  end

  def label
    name.gsub(" ","_").downcase.to_sym
  end

  def created_by_or_admin?(user)
    creator_id == user.id or user.has_role?(:admin)
  end

  def can_be_managed_by?(user)
    (created_by_or_admin?(user) or user.has_role?(:call_centre))
  end

  def list_of_fields
    result_fields.map(&:name).join(", ")
  end

  def send_material?
    result_fields.map(&:field_type).include?(ResultField::MATERIAL.to_s)
  end

  def upgrades_to_category_supplier?
    name == "Upgrade to category supplier"
  end

  def upgrades_to_supplier?
    name == "Upgrade to supplier"
  end

  def upgrades_to_member?
    name == "Upgrade to member"
  end

  def upgrades_to_any_user?
    upgrades_to_category_supplier? or upgrades_to_supplier? or upgrades_to_member?
  end

  def email_template_name_for_type
    if upgrades_to_member?
      "upgrade_contact_to_member"
    elsif upgrades_to_supplier?
      "upgrade_contact_to_buyer"
    elsif upgrades_to_category_supplier?
      "upgrade_contact_to_category_buyer"
    elsif send_material?
      "result_send_material"
    end
  end

  private

  def check_is_reported_and_is_success
    if call_results.any?
      if !is_reported? and is_reported_changed?
        self.errors.add(:is_reported, I18n.t("models.result_field.is_reported_cannot_be_disabled"))
      end
      if !is_success? and is_success_changed?
        self.errors.add(:is_success, I18n.t("models.result_field.is_success_cannot_be_disabled"))
      end
    end
  end
end

app/controllers/callers/results_controller.rb
class Callers::ResultsController < Callers::CallerController

  inherit_resources
  set_tab "campaigns"
  before_filter :set_campaign
  before_filter :set_result_type, :only => [:edit, :update, :destroy]
  before_filter lambda {authorize_role(:call_centre, :admin)}
  before_filter lambda {authorize_manage_rights(@result)}, :only => [:edit,:update,:destroy]

  def new
    @result = Result.new(:final => params[:type].eql?("final"))
  end

  def create
    @result = Result.new(params[:result])
    @result.creator = current_user
    create! do |success, failure|
      success.html { redirect_to callers_campaign_results_path(@campaign) }
      failure.html { render 'new' }
    end
  end

  def edit
  end

  def update
    @result.attributes = params[:result]
    if @result.save
      redirect_to callers_campaign_results_path(@campaign)
    else
     render 'edit' 
    end
  end

  def destroy
    destroy! do |success, failure|
      success.html { redirect_to callers_campaign_results_path(@campaign) }
      failure.html {}
    end
  end

  def batch_assign
    @campaign.assign_results(params)
    redirect_to edit_callers_campaign_path(@campaign)
  end

  protected

  def collection
    @results = Result
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:campaign_id])
  end

  def set_result_type
    @result = Result.find(params[:id])
  end


end

app/views/shared/results/_add_result_lead_fields.html.erb
<%= form.inputs :for => :contact do |f| %>
    <%= render :partial => '/shared/leads/form', :locals => {:form => f} %>
<% end %>

app/views/shared/results/_add_result_value_fields.html.erb
<% css_class = case f.object.result_field.field_type.to_i
    when ResultField::NOTE then
        'text'
    when ResultField::DATE then
        'date'
    when ResultField::DATETIME then
        'date time'
    when ResultField::MATERIAL then
        'text'    
    else
        'string'
end
%>


<li class="<%= css_class %>">
  <% abbr = f.object.result_field.is_mandatory ? content_tag(:abbr, "*").html_safe : '' -%>
  <%= raw f.label :value, h(f.object.result_field.name)+(abbr) %>
  <%= case f.object.result_field.field_type.to_i
      when ResultField::NOTE then
          f.text_area :value, :style => "height: 100px; width: 230px"
      when ResultField::DATE then
          f.text_field :value, :class => "datepicker", :title => t('models.result_field.date_format')
      when ResultField::DATETIME then
          f.text_field :value, :class => "datetimepicker", :title => t('models.result_field.datetime_format')
      when ResultField::MATERIAL then
          f.hidden_field :value, :id => "material_#{f.object.result_field.id}"
      else
          f.text_field :value
  end
  %>
  <%= custom_error_for_field(f, :value) %>
  <% if f.object.result_field.field_type.to_i == ResultField::MATERIAL %>
      <div class="txt">
        <p id="material_<%= f.object.result_field.id %>_name">
          <% if f.object.value.blank? %>
            <%= t("materials.views.index.no_file_selected")  %>
          <% else %>
            <% (contact.campaign.default_materials_set + f.object.materials).uniq.each do |material| %>
                  <%= check_box_tag "material_selected_#{material.id}", "1", params["material_selected_#{material.id}".to_sym].to_i == 1 %>
                  <%= material.filename %><br/>
            <% end %>
          <% end %>
        </p>
        <p style="padding-top:5px;">
          <%= bt_link_to_function :cog, t("materials.views.index.material_repository"), "$('#materials_dialog').load('#{callers_campaign_materials_path(contact.campaign, :format => :js, :result_field_id => f.object.result_field.id)}').dialog({title:'#{t('materials.views.index.select_or_upload')}', width:400, height:350, beforeClose: function(event, ui) { $('#materials_dialog').html('');return true; }})" %>
        </p>
      </div>
      <div class="txt">
          <p><%= label_tag "call_result[contact_email_address]", "#{t("materials.views.index.contact_email_address")}<abbr>*</abbr>".html_safe %><%= text_field_tag "call_result[contact_email_address]", call_result.contact_email_address || contact.email_address  %></p>
          <%= custom_error_for_object_and_field(call_result, :contact_email_address) %>
      </div>

      <script type="text/javascript">
        <% (contact.campaign.default_materials_set + f.object.materials).uniq.each do |material| %>
            <%= "select_file_from_repository('#{f.object.result_field.id}', #{material.id}, '#{material.asset_file_name}');" %>
        <% end %>
      </script>
  <% end %>
</li>
<li class="hidden">
  <%= f.hidden_field :result_field_id, :value => f.object.result_field.id %>
</li>

<script type="text/javascript">
    jQuery(document).ready(function() {
        if ($('#materials_dialog').length == 0) {
            $('body').append('<div id="materials_dialog"></div>');
        }
    });

    $(function() {
        $(".datetimepicker").datetimepicker({ dateFormat: 'yy-mm-dd' });
        $(".datepicker").datepicker({ dateFormat: 'yy-mm-dd' });
    });
</script>

app/views/shared/results/_result_field_fields.html.erb
<div id="result_field_form_<%= f.object.new_record? ? 'result_result_fields_attributes_0' : f.object.id %>">
  <hl/>
  <div class="pdd_10 no_pdd_t">
    <fieldset class="inputs_vertical">
      <ol>
        <li class="string required <%= 'error' if f.object.errors[:name].present?%>">
          <label><%= t("shared.results.form.field_name") %><abbr title="required">*</abbr></label>
          <%= f.text_field :name %>
          <%= custom_error_for_field(f, :name) %>
        </li>
        <li class="select">
          <%= f.label :field_type %>
          <%= f.select :field_type, options_for_select(ResultField::FIELD_TYPES.map { |ft| [t("models.result_field.field_type.type#{ft}"), ft] }, f.object.field_type) %>
          <%= custom_error_for_field(f, :field_type) %>
        </li>
        <li class="boolean">
          <%= f.check_box :is_mandatory %>
          <%= f.label :is_mandatory %>
        </li>
        <li class="hidden">
          <% unless f.object.new_record? %>
              <%= f.hidden_field :_destroy, :id => "destroy_hidden_field_#{f.object.id}" %>
          <% end %>
        </li>
        <li class="commit">
          <%= bt_link_to :remove, t("shared.lead_templates.form.remove_lead_template_field"), "javascript:void(0)", :onclick => "remove_result_field('#{f.object.new_record? ? 'result_result_fields_attributes_0' : f.object.id}', #{f.object.new_record? ? 'null' : f.object.id})" %>
        </li>
      </ol>
    </fieldset>
  </div>
</div>

app/views/shared/results/_result_fields.html.erb
<div class="pdd_10 no_pdd_t">
  <fieldset class="inputs labels_ta_r labels_200">
      <ol>
        <%= form.fields_for :result_values, call_result.all_result_values(call_result.result) do |builder| %>
            <%= render :partial => "/shared/results/add_result_value_fields", :locals => {:f => builder, :contact => contact, :call_result => call_result} %>
        <% end %>
      </ol>
  </fieldset>
</div>