config/routes.rb
Nbs::Application.routes.draw do

  resources :payment_notifications

  get "agent_home/show"
  get "supplier_home/show"

  devise_for :users, :controllers => {:passwords => "users/passwords"}

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  match 'bulk_action' => 'bulk_actions#create', :as => :bulk_action

  namespace :administration do
    root :to => redirect("/")
    resources :users do
      resource :password, :controller => 'password', :only => [:new, :update, :destroy]
      member do
        get :sign_in_as
      end
    end
    resource :bulk_users_update, :controller => "bulk_users_update", :only => [:update]
    resources :categories
    resources :category_email_templates, :only => [:edit, :update]
    resource :setting, :only => [:edit, :update]
    resources :featured_deals, :only => [:index, :create]
    resources :email_templates
    resources :leads
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resources :articles
    resources :news
    resources :hints
    resources :currencies
    namespace :invoicing do
      resources :invoices do
        resources :invoice_lines
        resource :cash_flow, :only => [:new, :create], :controller => "CashFlow"
        resource :invoice_lines_payable, :only => :new, :controller => "InvoiceLinesPayable"
        resources :mailings, :only => [:new, :create]
        resource :seller, :only => [:update]
      end
      resource :bulk_mailings, :controller => "bulk_mailings", :only => [:edit, :update]
      resource :bulk_invoice_update, :controller => "bulk_invoice_update", :only => [:update]
      resource :bulk_invoice_users, :controller => "bulk_invoice_users", :only => [:update]
      resources :upcoming_invoices, :only => [:index]
      resources :payment_transactions
      resources :credit_notes
      resources :creditors
      resources :refunds
    end
    resources :bank_accounts
    resources :vat_rates
    resources :lead_templates
    resources :sellers
    resources :category_users
    resources :countries
    resource :translation do
      resource :cache
    end
    resource :stats_recalculation, :controller => "stats_recalculation", :only => [:update]
    resources :supplier_interests, :only => [:edit, :update]
    resources :youtube_introductions
    resources :email_bounces
    resources :languages
    resources :subscription_plans
  end

  namespace :suppliers do
    root :to => "lead_purchases#index"
    resources :cart_items
    resources :deal_certification_requests, :only => [:index, :edit, :update]
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :cart, :only => [:show, :update, :destroy], :controller => 'cart'
    resources :lead_purchases do
      collection do
        put :bulk_update
      end
      resource :lead_email, :only => [:new, :create]
    end
    resource :bulk_cart_items, :controller => "bulk_cart_items", :only => [:create]
  end
  match 'suppliers/bulk_lead_purchase_csv' => 'suppliers/bulk_lead_purchase_csv#create', :as => "bulk_lead_purchase_csv"
  match 'suppliers/bulk_lead_purchase_print' => 'suppliers/bulk_lead_purchase_print#create', :as => "bulk_lead_purchase_print"
  match 'suppliers/bulk_lead_purchase_update' => 'suppliers/bulk_lead_purchase_update#create', :as => "bulk_lead_purchase_update"
  match 'suppliers/bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#new', :as => "bulk_lead_share_by_email"
  match 'suppliers/create_bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#create', :as => "create_bulk_lead_share_by_email"

  namespace :call_centres do
    root :to => "call_centre_agents#index"
    resources :call_centre_agents do
      resource :password, :controller => 'password', :only => [:new, :update, :destroy]
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :bulk_call_centre_agents_update, :controller => "bulk_call_centre_agents_update", :only => [:update]
    resources :leads
    resources :lead_templates
    resources :news
  end

  namespace :call_centre_agents do
    root :to => "leads#index"
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :lead_users do
    root :to => "lead_purchases#index"
    resources :lead_purchases do
      resource :lead_email, :only => [:new, :create]
    end
    resources :lead_requests
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:create, :destroy]
    resource :bulk_lead_purchase_update, :controller => "bulk_lead_purchase_update", :only => [:create]
    resource :bulk_lead_purchase_csv, :controller => "bulk_lead_purchase_csv", :only => [:create]
    resource :bulk_lead_purchase_print, :controller => "bulk_lead_purchase_print", :only => [:create]
  end

  namespace :suppliers do
    root :to => redirect("/suppliers/lead_purchases")
    resource :interests, :only => [:edit, :update]
    resources :subaccounts
    resources :lead_requests, :only => [:index, :update, :destroy]
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:destroy, :update]
    resource :bulk_subaccounts_update, :controller => "bulk_subaccounts_update", :only => [:update]
    resources :not_invoiced_leads, :only => [:index]
    resources :invoices, :only => [:show, :index]
    resources :lead_templates
  end

  namespace :agents do
    root :to => "leads#index"
    resources :lead_templates
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :members do
    root :to => "leads#index"
    resources :leads, :path => :requests
    resources :tenders, :path => :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
  end

  namespace :callers do
    resources :campaigns do
      resources :materials
      member do
        get 'result_details'
        get 'result_details_to_csv'
        get 'contacts_for_search'
        post 'duplicate'
      end
      resources :results, :except => :show do
        collection do
          post 'batch_assign'
        end
      end
      resources :campaigns_users, :only => [:index, :update]
      resource :campaigns_description, :controller => "campaigns_description", :only => [:show, :edit, :update]
      resources :contacts do
        collection do
          post 'batch_remove'
          post 'batch_assign'
          post 'bulk_contacts_export_csv'
          post 'import_xls'
        end
      end
      resources :advanced_import, :only => [:create, :destroy] do
        collection do
          post 'choose'
          post 'preview'
        end
      end
      resources :agent_work_screen, :only => :index
      namespace :agent_work_screen do
        resources :contacts, :only => [:create, :show, :destroy, :update] do
          resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
        end
        resource :agent_information, :only => [:show]
        resource :call_sheet, :only => [:show]
        resource :pending_call, :only => [:show]
        resource :complete_contact, :only => [:show]
      end
      resources :email_templates, :only => [:edit, :update]
    end

    resource :production, :controller => "production", :only => [:show]

    resources :contacts do
      resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
    end

    resources :campaign_reports, :only => [:index] do
      collection do
        post 'load_agents'
      end
    end
  end

  namespace :comments do
    resources :threads
    resources :leads do
      resources :threads
    end
    resources :replies
    resources :blocked_conversations, :only => [:create, :destroy]
    resources :comment_readers, :only => [:create]
  end

  namespace :deal_comments do
    resources :threads
    resources :deals do
      resources :threads
    end
    resources :replies
    resources :comment_readers, :only => [:create]
  end

  match 'supplier_home' => 'supplier_home#show', :as => "supplier_home"
  match 'agent_home' => 'agent_home#show', :as => "agent_home"
  match 'member_home' => 'member_home#show', :as => "member_home"

  resources :leads, :except => [:new, :create, :destroy] do
    collection do
      post :creators
    end
  end

  resources :deals, :except => [:new, :create, :destroy] do
    member do
      post 'rate'
    end
  end

  resources :group_deals, :only => [:show]

  resources :categories, :only => [:index] do
    resources :more_leads_requests, :only => [:new, :create]
  end
  resources :deal_categories, :only => [:index]

  match 'categories/:slag' => "leads#index"
  match 'categories/deals/:slag' => "deals#index", :as => :deals_index

  resource :contacts_advanced_import, :only => [:create, :destroy, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :leads_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :members_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :suppliers_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resources :agent_accounts, :only => [:new, :create]
  resources :supplier_accounts, :only => [:new, :create]
  resources :member_accounts, :only => [:new, :create]
  resources :category_supplier_accounts, :only => [:new, :create]

app/controllers/administration/administration_controller.rb
class Administration::AdministrationController < SecuredController
  def current_user
    @admin ||= ::User::Admin.find_by_id(super.id)
    @admin ||= User.find_by_id(super.id).with_role
  end

  private

  def authorize_user_for_namespace!
    authorize_role(:admin)
  end

end

app/controllers/administration/articles_controller.rb
class Administration::ArticlesController < Administration::AdministrationController
  inherit_resources

  set_tab "content"
  set_subtab "articles"

  before_filter :set_referer, :only => [:edit]

  def edit
    @article = Article.find(params[:id])
    edit!
  end

  def update
    @article = Article.find(params[:id])
    @article.attributes = params[:article]
    update! do |success, failure|
      success.html {
      if session[:articles_referer]
        redirect_to session[:articles_referer]
      else
        redirect_to administration_articles_path
      end
      }
      failure.html { render :action => :edit }
    end
  end

  def create
    params[:article_cms] ||= {}
    @article = Article::Cms::MainPageArticle.new(params[:article])
    create! do |success, failure|
      success.html { render :action => :edit }
      failure.html { redirect_to administration_articles_path }
    end
  end

  protected

  def collection
    params[:search] ||= {}
    params[:search][:with_subclass] = "Article::Cms" unless params[:search][:with_subclass].present?
    params[:search][:without_subclass] = "Article::Cms::Hint"
    @search = Article.scoped_search(params[:search])
    @articles = @search.paginate(:page => params[:page])
  end

  private

  def authorize_user_for_namespace!
    authorize_role(:translator)
  end

  def set_referer
    session[:articles_referer] = request.referer
  end
end

app/controllers/administration/bank_accounts_controller.rb
class Administration::BankAccountsController < Administration::AdministrationController
  inherit_resources

  set_tab "settings"
  set_subtab "global"

  def update
    update! do |success,failure|
      success.html { redirect_to edit_administration_setting_path}
      failure.html { render :action => :edit }
    end
  end

  def create
    create! do |success,failure|
      success.html { redirect_to edit_administration_setting_path}
      failure.html { render :action => :new }
    end
  end

  def destroy
    destroy! do |format|
      format.html { redirect_to edit_administration_setting_path }
    end
  end

end

app/controllers/administration/bulk_users_update_controller.rb
class Administration::BulkUsersUpdateController < Administration::AdministrationController

  def update
    if params[:user_ids]
      User::Abstract.where(:id => params[:user_ids]).each do |user|
        if params[:bulk_action_type] == "create_invoice" and user.big_buyer?
          LeadPurchase.with_not_invoiced.where("owner_id = ?", user.id).each do |lead_purchase|
            Invoice.create(:user_id => user.id, :currency_id => lead_purchase.currency_id)
          end
        elsif params[:bulk_action_type].to_s.include?("lock")
          user.locked = params[:bulk_action_type]
          user.save
        end
      end
    end
    flash[:notice] = I18n.t("flash.bulk_users_update.update.notice")

    redirect_to administration_users_path
  end
end

app/controllers/administration/caches_controller.rb
class Administration::CachesController < Administration::AdministrationController

  def destroy
    begin
      I18n.cache_store.clear
    rescue
      #nothing
    end

    flash[:notice] = t("common.cache_cleared")
    redirect_to :back
  end

end

app/controllers/administration/categories_controller.rb
class Administration::CategoriesController < Administration::AdministrationController
  inherit_resources

  before_filter :set_category_type
  before_filter :set_tab, :only => [:new,:create]

  def new
    @category = @category_type.constantize.new(:buyout_enabled => false)
  end

  def create
    @category = @category_type.constantize.new(params[:category])
    @category.customers = []
    @category.agents = []
    respond_to do |format|
      if @category.save
        @category.customer_ids = params[:category][:customer_ids]
        @category.agent_ids = params[:category][:agent_ids]
        @category.save
        @category.move_leads_to_subcategory
        flash[:notice] = I18n.t("flash.categories.create.notice")
        format.html { redirect_to @category_type == "LeadCategory" ? categories_path : deal_categories_path }
      else
        @category.customer_ids = params[:category][:customer_ids]
        @category.agent_ids = params[:category][:agent_ids]
        format.html { render 'new' }
      end
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to @category.is_a?(LeadCategory) ? categories_path : deal_categories_path }
      failure.html { render 'edit' }
    end
  end

  def destroy
    destroy! do |success, failure|
      success.html {
        flash[:notice] = I18n.t("flash.categories.destroy.notice")
        redirect_to categories_path }
      failure.html {
        flash[:notice] = I18n.t("flash.categories.destroy.error")
        redirect_to categories_path }
    end
  end

  private

  def set_category_type
    @category_type = params[:category_type] || "LeadCategory"
  end

  def set_tab
    self.class.set_tab (@category_type == "LeadCategory" ? "browse_leads" : "browse_deals")
  end

  def resource
    @category = Category.find(params[:id])
    @category_type = @category.class.to_s
    set_tab
    @category
  end

end

app/controllers/administration/category_email_templates_controller.rb
class Administration::CategoryEmailTemplatesController < Administration::AdministrationController
  set_tab "browse_leads"

  before_filter :set_category, :only => [:edit, :update]

  def edit
    global_et = EmailTemplate.find_by_uniq_id('bought_lead_notification')
    @email_template = @category.email_template ? @category.email_template : @category.create_email_template(:subject => global_et.subject, :body => global_et.body, :from => global_et.from)
  end

  def update
    @email_template = @category.email_template
    @email_template.update_attributes(params[:email_template])
    if @email_template.save
      flash[:notice] = t('administration.category_email_templates.update.controller.successful_update_notice')
      redirect_to categories_path
    else
      render :edit
    end
  end

  private

  def set_category
    @category = LeadCategory.find(params[:id])
  end


end

app/controllers/administration/category_users_controller.rb
class Administration::CategoryUsersController < Administration::AdministrationController

  def index
    @users = (params[:users_type] == "customers" ? User.with_suppliers : User.with_agents)
    @users = @users.where("first_name like :query or last_name like :query or email like :query", { :query => "%#{params[:query]}%" }) if params[:query]
  end
end

app/controllers/administration/countries_controller.rb
class Administration::CountriesController < Administration::AdministrationController
  inherit_resources
  set_tab "settings"
  set_subtab "countries"

  def create
    create! do |success,failure|
      success.html { redirect_to administration_countries_path }
      failure.html { render :action => :new }
    end
  end

  def update
    update! do |success,failure|
      success.html { redirect_to administration_countries_path }
      failure.html { render :action => :edit }
    end
  end

  def destroy
    destroy! do |success,failure|
      success.html { redirect_to administration_countries_path }
      failure.html {
        flash[:alert] = @currency.errors[:base].join('<br/>')
        redirect_to administration_countries_path
      }
    end
  end
end

app/views/administration/countries/_form.html.erb
<div class="column_left">
  <div class="pdd_10 no_pdd_t">
    <fieldset class="inputs labels_ta_r labels_200">
      <ol class="align_inputs">
        <%= form.input :name %>
        <%= form.input :locale %>
        <%= form.input :detailed_locale %>
        <%= form.input :email_template_signature, :as => :text, :input_html => {:style => "width:230px;height:60px"} %>
      </ol>
    </fieldset>
  </div>
</div>

<div class="column_right">
  <div class="pdd_10 no_pdd_t">
    <fieldset class="inputs labels_ta_r labels_200">
      <ol class="align_inputs">
        <% if @country.logo and @country.logo.id %>
            <ol>
              <li class="string">
                <label><%= t("administration.countries.form.logo_label") %></label>

                <div class="txt assets_elements">
                  <ul>
                    <li>
                      <%= image_tag @country.logo.url %>
                    </li>
                  </ul>
                </div>
              </li>
            </ol>
        <% end %>
        <%= form.semantic_fields_for :logo, @country.logo || @country.build_logo do |logo_form| %>
            <ol>
            <%= logo_form.input :asset, :as => :file, :label => t("administration.countries.form.upload_logo_label") %>
            </ol>
      <% end %>
      </ol>
    </fieldset>
  </div>
</div>
<clb/>

<%= form.fields_for :regions, @country.regions do |builder| %>
    <%= render :partial => "region_fields", :locals => {:f => builder} %>
<% end %>

<div class="nested_region_fields_container"></div>

<hl/>
<div class="pdd_20" style="padding-top:10px">
  <%= bt_link_to :plus, t("administration.countries.form.new_region"), "javascript:void(0)", :onclick => "#{fields_for_region_fields(form)}" %>
</div>

<script>
    var nestedFormsCount = <%= @country.regions.size %>;

    function add_region(link, content) {
        var new_id = new Date().getTime();
        content = content.replace(/country_regions_attributes_\d+/g, "country_regions_attributes_" + nestedFormsCount.toString());
        content = content.replace(/country\[regions_attributes\]\[\d+\]/g, "country[regions_attributes][" + new_id.toString() + "]");
        $('.nested_region_fields_container:last').append(content);
        nestedFormsCount = nestedFormsCount + 1;
    }

    function remove_region(id, record_id) {
        nestedFormsCount = nestedFormsCount - 1;

        if (record_id == null) {
            $('#region_field_form_' + id).remove();
        }
        else {
            $('#region_field_form_' + id).hide();
            $('#destroy_hidden_field_' + record_id.toString()).val('true')
        }

    }
</script>

app/views/administration/countries/_region_fields.html.erb
<div id="region_field_form_<%= f.object.new_record? ? 'country_regions_attributes_0' : f.object.id %>">
  <hl/>
  <div class="pdd_10 no_pdd_t">
    <fieldset class="inputs_vertical">
      <ol>
        <li class="string required <%= 'error' if f.object.errors[:name].present?%>">
          <label><%= t("administration.countries.form.region_name") %><abbr title="required">*</abbr></label>
          <%= f.text_field :name %>
          <%= custom_error_for_field(f, :name) %>
        </li>
        <li class="hidden">
          <% unless f.object.new_record? %>
              <%= f.hidden_field :_destroy, :id => "destroy_hidden_field_#{f.object.id}" %>
          <% end %>
        </li>
        <li class="commit">
          <%= bt_link_to :remove, t("administration.countries.form.delete_region"), "javascript:void(0)", :onclick => "remove_region('#{f.object.new_record? ? 'country_regions_attributes_0' : f.object.id}', #{f.object.new_record? ? 'null' : f.object.id})" %>
        </li>
      </ol>
    </fieldset>
  </div>
</div>

app/views/administration/countries/edit.html.erb
<column-mc:>
  <header back="true"><%= t("administration.countries.edit.view.header", :name => @country.name) %></header>

  <%= semantic_form_for @country, :url => administration_country_path, :html => {:multipart => true} do |form| %>
      <frm title="#{@country.name}">
        <param:content>
          <%= render :partial => 'form', :locals => {:form => form} %>
        </param:content>
        <param:actions>
          <ibt c="fltri" icon="save">
            <%= form.submit t("administration.countries.edit.view.button_update_country") %>
          </ibt>
          <ibt c="bt_grey fltri">
            <%= button_to_function t("administration.countries.edit.view.button_cancel"), "history.go(-1)" %>
          </ibt>
        </param:actions>
      </frm>
  <% end %>
</column-mc:>

app/views/administration/countries/index.html.erb
<column-mc:>
  <header>
    <param:content>
      <%= t("administration.countries.index.view.title") %>
    </param:content>

    <param:actions>
      <ul class="header_actions">
        <li class="last">
          <%= bt_link_to :plus, t("administration.countries.index.view.new_country"), "javascript:void(0)", :onclick => "$('#form_new_country').submit()" %>
        </li>
      </ul>
    </param:actions>
  </header>

  <div class="hidden">
    <%= form_tag new_administration_vat_rate_path, :method => :get, :id => "form_new_country" do %>
        <%= submit_tag t("administration.countries.index.view.new_country") %>
    <% end %>
  </div>

  <% if @countries.blank? %>
      <%= blank_state_message( t("administration.countries.index.view.no_currencies_defined") ) %>
  <% else %>
      <table id="countries_table" class="generic">
        <thead>
        <tr>
          <th class="hl"></th>
          <th style="width:10px"><%= t("administration.countries.index.view.table.id") %></th>
          <th><%= t("administration.countries.index.view.table.name") %></th>
          <th><%= t("administration.countries.index.view.table.locale") %></th>
          <th class="ta_r"><%= t("administration.countries.index.view.table.actions") %></th>
          <th class="hr"></th>
        </tr>
        </thead>
        <tfoot>
        <tr>
          <td class="fl"></td>
          <td colspan="4"></td>
          <td class="fr"></td>
        </tr>
        </tfoot>
        <tbody>
        <% @countries.each do |country| %>
            <tr id="country_<%= country.id %>" class="<%= cycle("odd", "even") %>">
              <td class="cl"></td>
              <td class="ta_c"><%= country.id %></td>
              <td><%= country.name %></td>
              <td><%= "#{country.locale.to_s}#{'-'+country.detailed_locale.upcase if country.detailed_locale.present?}" %></td>
              <td class="tda ta_r" id="country_actions_td_<%= country.name.gsub(" ", "_") %>">
                <ul-actions>
                  <li>
                    <%= link_to t("administration.countries.index.view.edit"), edit_administration_country_path(country), :class => "default_action" %>
                  </li>
                  <% if country.can_be_destroyed? %>
                    <li>
                      <%= link_to t("administration.countries.index.view.delete"), administration_country_path(country), {:method => :delete, :confirm => t("administration.countries.index.view.delete_confirmation_message")} %>
                    </li>
                  <% end %>
                </ul-actions>
              </td>
              <td class="cr"></td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% end %>
</column-mc:>

app/views/administration/countries/new.html.erb
<column-mc:>
  <header back="true"><%= t("administration.countries.new.view.header") %></header>

  <%= semantic_form_for @country, :url => administration_countries_path, :html => {:multipart => true} do |form| %>
      <frm title="">
        <param:content>
          <%= render :partial => 'form', :locals => {:form => form} %>
        </param:content>
        <param:actions>
          <ibt c="fltri" icon="save">
            <%= form.submit t("administration.countries.new.view.button_create_country") %>
          </ibt>
          <ibt c="bt_grey fltri">
            <%= button_to_function t("administration.countries.new.view.button_cancel"), "history.go(-1)" %>
          </ibt>
        </param:actions>
      </frm>
  <% end %>
</column-mc:>