config/routes.rb
Nbs::Application.routes.draw do

  resources :payment_notifications

  get "agent_home/show"
  get "supplier_home/show"

  devise_for :users, :controllers => {:passwords => "users/passwords"}

  devise_for :users do
    get "login", :to => "devise/sessions#new"
    get "logout", :to => "devise/sessions#destroy"
  end

  match 'bulk_action' => 'bulk_actions#create', :as => :bulk_action

  namespace :administration do
    root :to => redirect("/")
    resources :users do
      resource :password, :controller => 'password', :only => [:new, :update, :destroy]
      member do
        get :sign_in_as
      end
    end
    resource :bulk_users_update, :controller => "bulk_users_update", :only => [:update]
    resources :categories
    resources :category_email_templates, :only => [:edit, :update]
    resource :setting, :only => [:edit, :update]
    resources :featured_deals, :only => [:index, :create]
    resources :email_templates
    resources :leads
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resources :articles
    resources :news
    resources :hints
    resources :currencies
    namespace :invoicing do
      resources :invoices do
        resources :invoice_lines
        resource :cash_flow, :only => [:new, :create], :controller => "CashFlow"
        resource :invoice_lines_payable, :only => :new, :controller => "InvoiceLinesPayable"
        resources :mailings, :only => [:new, :create]
        resource :seller, :only => [:update]
      end
      resource :bulk_mailings, :controller => "bulk_mailings", :only => [:edit, :update]
      resource :bulk_invoice_update, :controller => "bulk_invoice_update", :only => [:update]
      resource :bulk_invoice_users, :controller => "bulk_invoice_users", :only => [:update]
      resources :upcoming_invoices, :only => [:index]
      resources :payment_transactions
      resources :credit_notes
      resources :creditors
      resources :refunds
    end
    resources :bank_accounts
    resources :vat_rates
    resources :lead_templates
    resources :sellers
    resources :category_users
    resources :countries
    resource :translation do
      resource :cache
    end
    resource :stats_recalculation, :controller => "stats_recalculation", :only => [:update]
    resources :supplier_interests, :only => [:edit, :update]
    resources :youtube_introductions
    resources :email_bounces
    resources :languages
    resources :subscription_plans
  end

  namespace :suppliers do
    root :to => "lead_purchases#index"
    resources :cart_items
    resources :deal_certification_requests, :only => [:index, :edit, :update]
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :cart, :only => [:show, :update, :destroy], :controller => 'cart'
    resources :lead_purchases do
      collection do
        put :bulk_update
      end
      resource :lead_email, :only => [:new, :create]
    end
    resource :bulk_cart_items, :controller => "bulk_cart_items", :only => [:create]
  end
  match 'suppliers/bulk_lead_purchase_csv' => 'suppliers/bulk_lead_purchase_csv#create', :as => "bulk_lead_purchase_csv"
  match 'suppliers/bulk_lead_purchase_print' => 'suppliers/bulk_lead_purchase_print#create', :as => "bulk_lead_purchase_print"
  match 'suppliers/bulk_lead_purchase_update' => 'suppliers/bulk_lead_purchase_update#create', :as => "bulk_lead_purchase_update"
  match 'suppliers/bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#new', :as => "bulk_lead_share_by_email"
  match 'suppliers/create_bulk_lead_share_by_email' => 'suppliers/bulk_lead_share_by_email#create', :as => "create_bulk_lead_share_by_email"

  namespace :call_centres do
    root :to => "call_centre_agents#index"
    resources :call_centre_agents do
      resource :password, :controller => 'password', :only => [:new, :update, :destroy]
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
    resource :bulk_call_centre_agents_update, :controller => "bulk_call_centre_agents_update", :only => [:update]
    resources :leads
    resources :lead_templates
    resources :news
  end

  namespace :call_centre_agents do
    root :to => "leads#index"
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :lead_users do
    root :to => "lead_purchases#index"
    resources :lead_purchases do
      resource :lead_email, :only => [:new, :create]
    end
    resources :lead_requests
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:create, :destroy]
    resource :bulk_lead_purchase_update, :controller => "bulk_lead_purchase_update", :only => [:create]
    resource :bulk_lead_purchase_csv, :controller => "bulk_lead_purchase_csv", :only => [:create]
    resource :bulk_lead_purchase_print, :controller => "bulk_lead_purchase_print", :only => [:create]
  end

  namespace :suppliers do
    root :to => redirect("/suppliers/lead_purchases")
    resource :interests, :only => [:edit, :update]
    resources :subaccounts
    resources :lead_requests, :only => [:index, :update, :destroy]
    resource :bulk_lead_requests, :controller => "bulk_lead_requests", :only => [:destroy, :update]
    resource :bulk_subaccounts_update, :controller => "bulk_subaccounts_update", :only => [:update]
    resources :not_invoiced_leads, :only => [:index]
    resources :invoices, :only => [:show, :index]
    resources :lead_templates
  end

  namespace :agents do
    root :to => "leads#index"
    resources :lead_templates
    resources :leads do
      resources :certifications, :only => :create
    end
    resources :deals do
      resources :assets, :controller => "deal_assets", :only => [:create, :destroy]
    end
  end

  namespace :members do
    root :to => "leads#index"
    resources :leads, :path => :requests
    resources :tenders, :path => :leads do
      resources :certifications, :only => :create
    end
    resources :lead_templates
  end

  namespace :callers do
    resources :campaigns do
      resources :materials
      member do
        get 'result_details'
        get 'result_details_to_csv'
        get 'contacts_for_search'
        post 'duplicate'
      end
      resources :results, :except => :show do
        collection do
          post 'batch_assign'
        end
      end
      resources :campaigns_users, :only => [:index, :update]
      resource :campaigns_description, :controller => "campaigns_description", :only => [:show, :edit, :update]
      resources :contacts do
        collection do
          post 'batch_remove'
          post 'batch_assign'
          post 'bulk_contacts_export_csv'
          post 'import_xls'
        end
      end
      resources :advanced_import, :only => [:create, :destroy] do
        collection do
          post 'choose'
          post 'preview'
        end
      end
      resources :agent_work_screen, :only => :index
      namespace :agent_work_screen do
        resources :contacts, :only => [:create, :show, :destroy, :update] do
          resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
        end
        resource :agent_information, :only => [:show]
        resource :call_sheet, :only => [:show]
        resource :pending_call, :only => [:show]
        resource :complete_contact, :only => [:show]
      end
      resources :email_templates, :only => [:edit, :update]
    end

    resource :production, :controller => "production", :only => [:show]

    resources :contacts do
      resources :call_results, :only => [:new, :create, :edit, :update, :destroy]
    end

    resources :campaign_reports, :only => [:index] do
      collection do
        post 'load_agents'
      end
    end
  end

  namespace :comments do
    resources :threads
    resources :leads do
      resources :threads
    end
    resources :replies
    resources :blocked_conversations, :only => [:create, :destroy]
    resources :comment_readers, :only => [:create]
  end

  namespace :deal_comments do
    resources :threads
    resources :deals do
      resources :threads
    end
    resources :replies
    resources :comment_readers, :only => [:create]
  end

  match 'supplier_home' => 'supplier_home#show', :as => "supplier_home"
  match 'agent_home' => 'agent_home#show', :as => "agent_home"
  match 'member_home' => 'member_home#show', :as => "member_home"

  resources :leads, :except => [:new, :create, :destroy] do
    collection do
      post :creators
    end
  end

  resources :deals, :except => [:new, :create, :destroy] do
    member do
      post 'rate'
    end
  end

  resources :group_deals, :only => [:show]

  resources :categories, :only => [:index] do
    resources :more_leads_requests, :only => [:new, :create]
  end
  resources :deal_categories, :only => [:index]

  match 'categories/:slag' => "leads#index"
  match 'categories/deals/:slag' => "deals#index", :as => :deals_index

  resource :contacts_advanced_import, :only => [:create, :destroy, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :leads_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :members_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resource :suppliers_advanced_import, :only => [:create, :show] do
    collection do
      post 'choose'
      post 'preview'
    end
  end

  resources :agent_accounts, :only => [:new, :create]
  resources :supplier_accounts, :only => [:new, :create]
  resources :member_accounts, :only => [:new, :create]
  resources :category_supplier_accounts, :only => [:new, :create]

app/models/article/cms.rb
class Article::Cms < ::Article

  attr_accessor :force_destroy

  validates_uniqueness_of :key, :scope => :type, :allow_nil => true

  before_destroy :can_be_destroyed?

  def can_be_destroyed?
    key.blank? or force_destroy
  end

  def show_type
    I18n.t("administration.articles.index.view.#{self.class.name.split('::').last.underscore.pluralize}")
  end

end

app/models/article/cms/help_popup.rb
class ::Article::Cms::HelpPopup < ::Article::Cms

  has_many :assets, :as => :resource, :dependent => :destroy, :finder_sql =>
      'SELECT "assets".*' +
      'FROM "assets"' +
      'WHERE ("assets".resource_id = #{id} AND "assets".resource_type = \'Article::Cms::HelpPopup\')'

  validates_presence_of :key

end

app/models/article/cms/hint.rb
class ::Article::Cms::Hint < ::Article::Cms
   validates_presence_of :key

  def content_sanitized
    content.gsub(/\n/,"").gsub(/\r/,"").gsub(/[']/, '\\\\\'')
  end
end

app/controllers/administration/administration_controller.rb
class Administration::AdministrationController < SecuredController
  def current_user
    @admin ||= ::User::Admin.find_by_id(super.id)
    @admin ||= User.find_by_id(super.id).with_role
  end

  private

  def authorize_user_for_namespace!
    authorize_role(:admin)
  end

end

app/controllers/administration/articles_controller.rb
class Administration::ArticlesController < Administration::AdministrationController
  inherit_resources

  set_tab "content"
  set_subtab "articles"

  before_filter :set_referer, :only => [:edit]

  def edit
    @article = Article.find(params[:id])
    edit!
  end

  def update
    @article = Article.find(params[:id])
    @article.attributes = params[:article]
    update! do |success, failure|
      success.html {
      if session[:articles_referer]
        redirect_to session[:articles_referer]
      else
        redirect_to administration_articles_path
      end
      }
      failure.html { render :action => :edit }
    end
  end

  def create
    params[:article_cms] ||= {}
    @article = Article::Cms::MainPageArticle.new(params[:article])
    create! do |success, failure|
      success.html { render :action => :edit }
      failure.html { redirect_to administration_articles_path }
    end
  end

  protected

  def collection
    params[:search] ||= {}
    params[:search][:with_subclass] = "Article::Cms" unless params[:search][:with_subclass].present?
    params[:search][:without_subclass] = "Article::Cms::Hint"
    @search = Article.scoped_search(params[:search])
    @articles = @search.paginate(:page => params[:page])
  end

  private

  def authorize_user_for_namespace!
    authorize_role(:translator)
  end

  def set_referer
    session[:articles_referer] = request.referer
  end
end

app/controllers/administration/bank_accounts_controller.rb
class Administration::BankAccountsController < Administration::AdministrationController
  inherit_resources

  set_tab "settings"
  set_subtab "global"

  def update
    update! do |success,failure|
      success.html { redirect_to edit_administration_setting_path}
      failure.html { render :action => :edit }
    end
  end

  def create
    create! do |success,failure|
      success.html { redirect_to edit_administration_setting_path}
      failure.html { render :action => :new }
    end
  end

  def destroy
    destroy! do |format|
      format.html { redirect_to edit_administration_setting_path }
    end
  end

end

app/controllers/administration/bulk_users_update_controller.rb
class Administration::BulkUsersUpdateController < Administration::AdministrationController

  def update
    if params[:user_ids]
      User::Abstract.where(:id => params[:user_ids]).each do |user|
        if params[:bulk_action_type] == "create_invoice" and user.big_buyer?
          LeadPurchase.with_not_invoiced.where("owner_id = ?", user.id).each do |lead_purchase|
            Invoice.create(:user_id => user.id, :currency_id => lead_purchase.currency_id)
          end
        elsif params[:bulk_action_type].to_s.include?("lock")
          user.locked = params[:bulk_action_type]
          user.save
        end
      end
    end
    flash[:notice] = I18n.t("flash.bulk_users_update.update.notice")

    redirect_to administration_users_path
  end
end

app/controllers/administration/caches_controller.rb
class Administration::CachesController < Administration::AdministrationController

  def destroy
    begin
      I18n.cache_store.clear
    rescue
      #nothing
    end

    flash[:notice] = t("common.cache_cleared")
    redirect_to :back
  end

end

app/controllers/administration/categories_controller.rb
class Administration::CategoriesController < Administration::AdministrationController
  inherit_resources

  before_filter :set_category_type
  before_filter :set_tab, :only => [:new,:create]

  def new
    @category = @category_type.constantize.new(:buyout_enabled => false)
  end

  def create
    @category = @category_type.constantize.new(params[:category])
    @category.customers = []
    @category.agents = []
    respond_to do |format|
      if @category.save
        @category.customer_ids = params[:category][:customer_ids]
        @category.agent_ids = params[:category][:agent_ids]
        @category.save
        @category.move_leads_to_subcategory
        flash[:notice] = I18n.t("flash.categories.create.notice")
        format.html { redirect_to @category_type == "LeadCategory" ? categories_path : deal_categories_path }
      else
        @category.customer_ids = params[:category][:customer_ids]
        @category.agent_ids = params[:category][:agent_ids]
        format.html { render 'new' }
      end
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to @category.is_a?(LeadCategory) ? categories_path : deal_categories_path }
      failure.html { render 'edit' }
    end
  end

  def destroy
    destroy! do |success, failure|
      success.html {
        flash[:notice] = I18n.t("flash.categories.destroy.notice")
        redirect_to categories_path }
      failure.html {
        flash[:notice] = I18n.t("flash.categories.destroy.error")
        redirect_to categories_path }
    end
  end

  private

  def set_category_type
    @category_type = params[:category_type] || "LeadCategory"
  end

  def set_tab
    self.class.set_tab (@category_type == "LeadCategory" ? "browse_leads" : "browse_deals")
  end

  def resource
    @category = Category.find(params[:id])
    @category_type = @category.class.to_s
    set_tab
    @category
  end

end

app/controllers/administration/category_email_templates_controller.rb
class Administration::CategoryEmailTemplatesController < Administration::AdministrationController
  set_tab "browse_leads"

  before_filter :set_category, :only => [:edit, :update]

  def edit
    global_et = EmailTemplate.find_by_uniq_id('bought_lead_notification')
    @email_template = @category.email_template ? @category.email_template : @category.create_email_template(:subject => global_et.subject, :body => global_et.body, :from => global_et.from)
  end

  def update
    @email_template = @category.email_template
    @email_template.update_attributes(params[:email_template])
    if @email_template.save
      flash[:notice] = t('administration.category_email_templates.update.controller.successful_update_notice')
      redirect_to categories_path
    else
      render :edit
    end
  end

  private

  def set_category
    @category = LeadCategory.find(params[:id])
  end


end

app/controllers/administration/category_users_controller.rb
class Administration::CategoryUsersController < Administration::AdministrationController

  def index
    @users = (params[:users_type] == "customers" ? User.with_suppliers : User.with_agents)
    @users = @users.where("first_name like :query or last_name like :query or email like :query", { :query => "%#{params[:query]}%" }) if params[:query]
  end
end

app/views/administration/articles/_form.html.erb
<div class="pdd_10 no_pdd_t">
  <fieldset class="inputs labels_100 labels_ta_r">
    <ol>
      <%= form.input :title %>
      <%= form.input :content,
                        :as => :ckeditor,
                        :label => false,
                        :input_html => {
                            :width => '1085px',
                            :height => '300px',
                            :swf_params => {
                                :resource_type => @article.class.name,
                                :resource_id => @article.id
                                }
                            } %>
      <%= form.input :published %>
    </ol>
  </fieldset>
</div>

app/views/administration/articles/edit.html.erb
<column-mc:>
  <%= javascript_include_tag :ckeditor %>
  <header back="true">
    <%= t('administration.articles.edit.view.header', :name => @article.title) %><%= image_tag_for_locale %>
  </header>


  <%= form_for @article, :as => :article, :url => administration_article_path(@article), :html => {:method => :delete, :id => "delete_article_form"} do |form| %>
  <% end %>

  <%= semantic_form_for @article, :as => :article, :url => administration_article_path(@article), :input_html => {:method => :put} do |form| %>
      <frm title="#{@article.title}">
        <param:content>
          <%= render :partial => 'form', :locals => {:form => form} %>
        </param:content>
        <param:actions>
          <ibt c="fltri" icon="save">
            <%= form.submit t("administration.articles.edit.view.button_save") %>
          </ibt>
          <ibt c="fltri bt_grey">
            <% if @article.just_created %>
              <%= button_to_function t("common.cancel_link"), "$('#delete_article_form').submit();"  %>
            <% else %>
              <%= button_to_function t("common.cancel_link"), "history.go(-1)" %>
            <% end %>
            </ibt>
        </param:actions>
      </frm>
  <% end %>
</column-mc:>

app/views/administration/articles/index.html.erb
<search-box:>
  <div class="search_box">
    <h2><%= t("common.search") %></h2>

    <div class="search_content">
      <%= form_for @search, :url => administration_articles_path do |f| %>
          <fieldset class="inputs_vertical">
            <ol class="no_pdd">
              <li class="string">
                <%= f.label :with_keyword, t("administration.leads.index.search.keyword_label") %>
                <%= f.text_field :with_keyword %>
              </li>
              <li class="select">
                <%= f.label :with_subclass, t("administration.leads.index.search.article_label") %>
                <%= f.select :with_subclass, article_scope_for_select, :include_blank => true %>
              </li>

              <li class="commit">
                <ibt c="bt_green" icon="magnify">
                  <%= submit_tag t("administration.articles.index.view.search_button") %>
                </ibt>
                <p>
                  <%= bt_clear_filter %>
                </p>
              </li>
            </ol>
          </fieldset>
      <% end %>
    </div>
  </div>
</search-box:>

<column-mc:>

  <header>
    <param:content>
      <%= t("administration.articles.index.view.header") %>
    </param:content>

    <param:actions>
      <%= form_tag administration_articles_path, :method => :post, :id => "form_new_article" do %>
          <ul class="header_actions">
            <li class="last">
              <%= bt_link_to :plus, t("administration.articles.index.view.new_article"), "javascript:void(0)", :onclick => "$('#form_new_article').submit()" %>
            </li>
          </ul>
      <% end %>
    </param:actions>
  </header>

  <% if @articles.blank? %>
      <%= blank_state_message %>
  <% else %>
      <table id="articles_table" class="generic">
        <thead>
        <tr>
          <th class="hl"></th>
          <th style="width: 10px"><%= link_to t("administration.articles.index.view.id"), order_for_scoped_search(:id) %></th>
          <th><%= t("administration.articles.index.view.type") %></th>
          <th><%= link_to t("administration.articles.index.view.title"), order_for_scoped_search(:title) %></th>
          <th class="ta_r"><%= t("administration.articles.index.view.actions") %></th>
          <th class="hr"></th>
        </tr>
        </thead>
        <tfoot>
        <tr>
          <td class="fl"></td>
          <td colspan="4"></td>
          <td class="fr"></td>
        </tr>
        </tfoot>
        <tbody>
        <% @articles.each do |article| %>
            <tr class="<%= cycle("odd", "even") %>">
              <td class="cl"></td>
              <td class="ta_c"><%= article.id %></td>
              <td><%= article.show_type %></td>
              <td><%= article.title %></td>
              <td class="tda ta_r">
                <ul-actions>
                  <li>
                    <%= link_to t("administration.articles.index.view.edit_link"), edit_administration_article_path(article), :class => "default_action" %>
                  </li>
                  <li>
                    <%= link_to t("administration.articles.index.view.show_link"), administration_article_path(article) %>
                  </li>
                  <% if article.can_be_destroyed? %>
                      <li>
                        <%= link_to t("administration.articles.index.view.delete_link"), administration_article_path(article), :method => :delete, :confirm => t("administration.articles.index.view.delete_confirmation") %>
                      </li>
                  <% end %>
                </ul-actions>
              </td>
              <td class="cr"></td>
            </tr>
        <% end %>
        <% if will_paginate %>
            <tr class="pagination">
              <td colspan="6" class="ta_c">
                <%= will_paginate @hints, :previous_label => '&laquo;', :next_label => '&raquo;' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% end %>
</column-mc:>

app/views/administration/articles/show.html.erb
<column-mc:>
  <header back="true"><%= t('administration.articles.show.view.header') %></header>

  <frm title="#{@article.title}">
    <param:header>
      <%= bt_link_to nil, t("common.edit_link"), edit_administration_article_path, :class => "fltr" %>
    </param:header>
    <param:content>
      <div class="pdd_10">
        <%= raw @article.content %>
      </div>
    </param:content>
  </frm>

</column-mc:>